default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
  host: ec2-54-246-104-52.eu-west-1.compute.amazonaws.com
  database: dfdkb9f1l3sjj4
  user: xpmgqlakseiodx
  port: 5432
  password: 1jBUv1vG3lUSr0rU_3UQi6Sbl2

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default