# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b796cf907f70c82239963549b5266dcb1297b7f4deeff00921e52bada1cd628598f1564bb02af498e676c80db115687a694e0f8cca4e2c5f6fcc5976e743212

test:
  secret_key_base: 5ecc506417418184181ce295deacd91229b56f617ac2e7bb6fd33c22d9f087744c5841f730cc3f0e43da9ffde7ef1883f80cf918a907a8e8ba14b8237b7801e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
